-- GENERATED by scripts/gen-seed.mjs from src/data/instrument.v0.json — do not edit by hand.
-- Run after migrations (supabase db reset runs this automatically, or paste into the SQL editor).

insert into public.instrument_versions (version, scoring_version, status, definition)
values ('v0', 'v0.1.0', 'active', $json$
{
  "version": "v0",
  "scoringVersion": "v0.1.0",
  "locales": ["en", "es"],
  "note": "Illustrative v0 instrument — subject to researcher revision. Items are data-driven and versioned; never hard-code into UI or scoring.",
  "items": [
    {
      "key": "age_band",
      "question_domain": "screener",
      "tier": "exposure",
      "type": "single_select",
      "scored": false,
      "order": 1,
      "text": { "en": "How old are you?", "es": "¿Cuántos años tienes?" },
      "options": [
        { "value": "13_17", "text": { "en": "13–17", "es": "13–17" } },
        { "value": "18_22", "text": { "en": "18–22", "es": "18–22" } },
        { "value": "23_30", "text": { "en": "23–30", "es": "23–30" } }
      ]
    },
    {
      "key": "heard_story",
      "question_domain": "screener",
      "tier": "exposure",
      "type": "yes_no",
      "scored": true,
      "order": 2,
      "text": {
        "en": "Have you had the chance to hear the story of Jesus?",
        "es": "¿Has tenido la oportunidad de escuchar la historia de Jesús?"
      }
    },
    {
      "key": "orientation",
      "question_domain": "screener",
      "tier": "exposure",
      "type": "single_select",
      "scored": false,
      "order": 3,
      "text": {
        "en": "Which of these is most like you right now?",
        "es": "¿Cuál de estas frases te describe mejor ahora?"
      },
      "options": [
        { "value": "confident_no_god", "text": { "en": "Confident God does not exist", "es": "Seguro de que Dios no existe" } },
        { "value": "open_not_exploring", "text": { "en": "Open, but not exploring", "es": "Abierto, pero sin explorar" } },
        { "value": "open_exploring", "text": { "en": "Open, and actively exploring", "es": "Abierto y explorando activamente" } },
        { "value": "other_religion", "text": { "en": "God exists, but I follow another religion", "es": "Dios existe, pero sigo otra religión" } },
        { "value": "interested_jesus", "text": { "en": "Interested in Jesus, want to know more", "es": "Interesado en Jesús, quiero saber más" } },
        { "value": "new_follower", "text": { "en": "New follower of Jesus", "es": "Nuevo seguidor de Jesús" } },
        { "value": "committed_growing", "text": { "en": "Committed, actively growing", "es": "Comprometido y creciendo" } }
      ]
    },

    {
      "key": "follow_jesus_god",
      "question_domain": "follow",
      "tier": "response",
      "type": "likert_5",
      "scored": true,
      "order": 10,
      "text": {
        "en": "I am a follower of Jesus, whom I believe is God.",
        "es": "Soy un seguidor de Jesús, a quien creo que es Dios."
      }
    },
    {
      "key": "forgiveness_through_jesus",
      "question_domain": "follow",
      "tier": "response",
      "type": "likert_5",
      "scored": true,
      "order": 11,
      "text": {
        "en": "I believe forgiveness of sins is only possible through faith in Jesus.",
        "es": "Creo que el perdón de los pecados solo es posible mediante la fe en Jesús."
      }
    },
    {
      "key": "experience_over_bible",
      "question_domain": "follow",
      "tier": "response",
      "type": "likert_5",
      "scored": true,
      "reverse_scored": true,
      "order": 12,
      "text": {
        "en": "I look to my own experiences more than the Bible to understand who I am.",
        "es": "Recurro más a mis propias experiencias que a la Biblia para entender quién soy."
      }
    },
    {
      "key": "decide_by_feeling",
      "question_domain": "follow",
      "tier": "response",
      "type": "likert_5",
      "scored": true,
      "reverse_scored": true,
      "order": 13,
      "text": {
        "en": "I usually decide what I believe based on what feels right to me.",
        "es": "Normalmente decido lo que creo según lo que me parece correcto."
      }
    },
    {
      "key": "becoming_like_jesus",
      "question_domain": "follow",
      "tier": "formation",
      "type": "likert_5",
      "scored": true,
      "order": 14,
      "text": {
        "en": "By God's grace, I am becoming more like Jesus in daily life.",
        "es": "Por la gracia de Dios, cada día me parezco más a Jesús."
      }
    },
    {
      "key": "pray_frequency",
      "question_domain": "follow",
      "tier": "formation",
      "type": "frequency",
      "scored": true,
      "scale": { "points": 4 },
      "order": 15,
      "core_activity": true,
      "text": { "en": "I pray to God.", "es": "Oro a Dios." },
      "options": [
        { "value": 0, "text": { "en": "Rarely or never", "es": "Casi nunca" } },
        { "value": 1, "text": { "en": "Monthly", "es": "Mensualmente" } },
        { "value": 2, "text": { "en": "Weekly", "es": "Semanalmente" } },
        { "value": 3, "text": { "en": "Most days", "es": "Casi todos los días" } }
      ]
    },
    {
      "key": "scripture_frequency",
      "question_domain": "follow",
      "tier": "formation",
      "type": "frequency",
      "scored": true,
      "scale": { "points": 4 },
      "order": 16,
      "core_activity": true,
      "text": { "en": "I read or hear scripture.", "es": "Leo o escucho las Escrituras." },
      "options": [
        { "value": 0, "text": { "en": "Rarely or never", "es": "Casi nunca" } },
        { "value": 1, "text": { "en": "Monthly", "es": "Mensualmente" } },
        { "value": 2, "text": { "en": "Weekly", "es": "Semanalmente" } },
        { "value": 3, "text": { "en": "Most days", "es": "Casi todos los días" } }
      ]
    },

    {
      "key": "jesus_only_way",
      "question_domain": "mission",
      "tier": "response",
      "type": "likert_5",
      "scored": true,
      "order": 20,
      "text": {
        "en": "Jesus is the only way to truly know God.",
        "es": "Jesús es el único camino para conocer verdaderamente a Dios."
      }
    },
    {
      "key": "sharing_optional",
      "question_domain": "mission",
      "tier": "response",
      "type": "likert_5",
      "scored": true,
      "reverse_scored": true,
      "order": 21,
      "text": {
        "en": "Sharing the message of Jesus is optional for someone who follows Him.",
        "es": "Compartir el mensaje de Jesús es opcional para quien lo sigue."
      }
    },
    {
      "key": "grow_in_community",
      "question_domain": "mission",
      "tier": "formation",
      "type": "yes_no",
      "scored": true,
      "order": 22,
      "text": {
        "en": "Following Jesus is something I grow in through relationships with other Christians.",
        "es": "Sigo a Jesús creciendo a través de relaciones con otros cristianos."
      }
    },
    {
      "key": "look_for_opportunities_share",
      "question_domain": "mission",
      "tier": "multiplication",
      "type": "likert_5",
      "scored": true,
      "order": 23,
      "text": {
        "en": "I look for opportunities to share my faith with others.",
        "es": "Busco oportunidades para compartir mi fe con otros."
      }
    },
    {
      "key": "shared_faith_6mo",
      "question_domain": "mission",
      "tier": "multiplication",
      "type": "yes_no",
      "scored": true,
      "order": 24,
      "text": {
        "en": "In the last 6 months, have you shared about Jesus with someone who doesn't follow Him?",
        "es": "En los últimos 6 meses, ¿has hablado de Jesús con alguien que no lo sigue?"
      }
    },
    {
      "key": "relationships_over_truth",
      "question_domain": "mission",
      "tier": "multiplication",
      "type": "likert_5",
      "scored": true,
      "reverse_scored": true,
      "order": 25,
      "text": {
        "en": "It is more important to maintain relationships than to speak the truth about Jesus.",
        "es": "Es más importante mantener las relaciones que decir la verdad sobre Jesús."
      }
    },

    {
      "key": "faith_real_good",
      "question_domain": "world",
      "tier": "response",
      "type": "likert_5",
      "scored": true,
      "order": 30,
      "text": {
        "en": "Following Jesus leads to real good for people and the world.",
        "es": "Seguir a Jesús produce un bien real para las personas y el mundo."
      }
    },
    {
      "key": "faith_shapes_life",
      "question_domain": "world",
      "tier": "formation",
      "type": "likert_5",
      "scored": true,
      "order": 31,
      "text": {
        "en": "My faith shapes how I live and act in the world around me.",
        "es": "Mi fe moldea cómo vivo y actúo en el mundo que me rodea."
      }
    },
    {
      "key": "bigger_than_self",
      "question_domain": "world",
      "tier": "formation",
      "type": "likert_5",
      "scored": true,
      "order": 32,
      "text": {
        "en": "My life is directed toward something bigger than just myself.",
        "es": "Mi vida está dirigida hacia algo más grande que yo mismo."
      }
    },
    {
      "key": "faith_personal_not_world",
      "question_domain": "world",
      "tier": "formation",
      "type": "likert_5",
      "scored": true,
      "reverse_scored": true,
      "order": 33,
      "text": {
        "en": "My faith is mainly about my personal life, not about making a difference in the world.",
        "es": "Mi fe se trata sobre todo de mi vida personal, no de marcar una diferencia en el mundo."
      }
    },
    {
      "key": "give_to_poor",
      "question_domain": "world",
      "tier": "multiplication",
      "type": "likert_5",
      "scored": true,
      "order": 34,
      "text": {
        "en": "Following Jesus includes giving time or money toward loving people who are poor, vulnerable and on the edge of society.",
        "es": "Seguir a Jesús incluye dar tiempo o dinero para amar a los pobres, vulnerables y marginados."
      }
    }
  ]
}
$json$::jsonb)
on conflict (version) do update
  set definition = excluded.definition,
      scoring_version = excluded.scoring_version,
      status = excluded.status;

insert into public.items (instrument_version_id, key, question_domain, tier, type, scored, reverse_scored, scale, ord)
select iv.id, e->>'key', e->>'question_domain', e->>'tier', e->>'type',
       coalesce((e->>'scored')::boolean, true),
       coalesce((e->>'reverse_scored')::boolean, false),
       e->'scale', (e->>'order')::int
from public.instrument_versions iv,
     lateral jsonb_array_elements(iv.definition->'items') e
where iv.version = 'v0'
on conflict (instrument_version_id, key) do update
  set question_domain = excluded.question_domain, tier = excluded.tier, type = excluded.type,
      scored = excluded.scored, reverse_scored = excluded.reverse_scored, scale = excluded.scale, ord = excluded.ord;

insert into public.organisations (slug, name, brand_color, region, country, website_domain, membership_tier, verified)
values ('sunrise', 'Sunrise Youth Collective', '#e0742f', 'Latin America', 'Argentina', 'sunriseyouth.org', 'collab_member', true)
on conflict (slug) do update
  set name = excluded.name, brand_color = excluded.brand_color, region = excluded.region,
      country = excluded.country, website_domain = excluded.website_domain, verified = excluded.verified;

insert into public.campaigns (org_id, slug, instrument_version_id, scoring_version, locale, active, source_label)
select o.id, 'default', iv.id, 'v0.1.0', 'en', true, 'seed'
from public.organisations o, public.instrument_versions iv
where o.slug = 'sunrise' and iv.version = 'v0'
on conflict (org_id, slug) do update
  set instrument_version_id = excluded.instrument_version_id, active = excluded.active;
