// Generates supabase/seed.sql from the canonical instrument JSON.
// The instrument definition is embedded once; items are derived from it in SQL.
import { readFileSync, writeFileSync } from "node:fs";

const json = readFileSync(new URL("../src/data/instrument.v0.json", import.meta.url), "utf8").trim();

const sql = `-- GENERATED by scripts/gen-seed.mjs from src/data/instrument.v0.json — do not edit by hand.
-- Run after migrations (supabase db reset runs this automatically, or paste into the SQL editor).

insert into public.instrument_versions (version, scoring_version, status, definition)
values ('v0', 'v0.1.0', 'active', $json$
${json}
$json$::jsonb)
on conflict (version) do update
  set definition = excluded.definition,
      scoring_version = excluded.scoring_version,
      status = excluded.status;

insert into public.items (instrument_version_id, key, question_domain, tier, type, scored, reverse_scored, scale, ord)
select iv.id, e->>'key', e->>'question_domain', e->>'tier', e->>'type',
       coalesce((e->>'scored')::boolean, true),
       coalesce((e->>'reverse_scored')::boolean, false),
       e->'scale', (e->>'order')::int
from public.instrument_versions iv,
     lateral jsonb_array_elements(iv.definition->'items') e
where iv.version = 'v0'
on conflict (instrument_version_id, key) do update
  set question_domain = excluded.question_domain, tier = excluded.tier, type = excluded.type,
      scored = excluded.scored, reverse_scored = excluded.reverse_scored, scale = excluded.scale, ord = excluded.ord;

insert into public.organisations (slug, name, brand_color, region, country, website_domain, membership_tier, verified)
values ('sunrise', 'Sunrise Youth Collective', '#e0742f', 'Latin America', 'Argentina', 'sunriseyouth.org', 'collab_member', true)
on conflict (slug) do update
  set name = excluded.name, brand_color = excluded.brand_color, region = excluded.region,
      country = excluded.country, website_domain = excluded.website_domain, verified = excluded.verified;

insert into public.campaigns (org_id, slug, instrument_version_id, scoring_version, locale, active, source_label)
select o.id, 'default', iv.id, 'v0.1.0', 'en', true, 'seed'
from public.organisations o, public.instrument_versions iv
where o.slug = 'sunrise' and iv.version = 'v0'
on conflict (org_id, slug) do update
  set instrument_version_id = excluded.instrument_version_id, active = excluded.active;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log("wrote supabase/seed.sql", sql.length, "bytes");
